# T\u00d4N TR\u1eccNG T\u00c1C GI\u1ea2 !!!!
# IMEI
imei=4b892043-1a3d-4f09-9bba-6d56094e49e0-76a02e3b7c9b39b51bd1ef658e740b35

# USERAGENT
userAgent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36 Edg/142.0.0.0

# LANGUAGE
language=vi

# ========== BOT SETTINGS ==========
# PREFIX
prefix=.

# LOGIN ID | M\u1eb7c \u0110\u1ecbnh Default Kh\u00f4ng C\u1ea7n S\u1eeda
loginId=default

# LISTEN
selfListen=true

# LOGIN LOG
logging=false

# ========== ZALO API SETTINGS ==========
# API TYPE
apiType=30

# API VERSION
apiVersion=670

# ========== DATABASE SETTINGS ==========
# MySQL Database Configuration (Connects to 2 databases)
db.host=localhost
db.port=3306
db.username=root
db.password=
db.name.a=jar1
db.name.b=jar1

# ========== NRO HTTP SERVER ==========
# NRO HTTP Server Port
nroHttpPort=8888
